version: '3.8'
services:
  postgres_db:
    image: postgres:11.7
    container_name: posttest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-vol:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-vol:
    external: true