---
- name: donwload and unarchive the app
  unarchive:
    src: "https://github.com/lassizci/postdo/releases/download/v1.1/postdo-v1.1.tar.gz"
    dest: /usr/local/bin
    creates: /usr/local/bin/postdo
    mode: 0755
    remote_src: yes
  notify:
    - restart postdo service

- name: configure postdo systemd unit
  template:
    src: postdo.service.j2
    dest: /etc/systemd/system/postdo.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd

- name: configure postdo
  template:
    src: postdo.j2
    dest: /etc/default/postdo
    owner: root
    group: root
    mode: 644
  notify:
    - restart postdo service

- name: ensure postdo is enabled and running
  service:
    name: postdo
    enabled: yes
    state: started
