apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alphascaler.fullname" . }}
  labels:
{{ include "alphascaler.labels" . | indent 4 }}
data:
  api_server_with_port: {{ .Values.config.api_server_with_port | quote }}
  db_endpoint: {{ .Values.config.db_endpoint | quote }}
  db_name: {{ .Values.config.db_name | quote }}
