{{- if .Values.image.pullSecrets.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-creds-harbor
  labels:
{{ include "alphascaler.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }} 
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alphascaler.fullname" . }}
  labels:
{{ include "alphascaler.labels" . | indent 4 }}
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  db_user: {{ .Values.secrets.db_user | b64enc | quote }}
  db_password:  {{ .Values.secrets.db_password | b64enc | quote }}
  api_auth_key:  {{ .Values.secrets.api_auth_key | b64enc | quote }}