{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "alphascaler.serviceAccountName" . }}
  labels:
{{ include "alphascaler.labels" . | indent 4 }}
{{- end -}}
